version: '3'
services:
  config-server:
    build: ./config-server
    image: rrun/config-server-k8s
    ports:
      - "8888:8888"
  discovery-server:
    build: ./discovery-server
    image: rrun/discovery-server-k8s
    ports:
      - "8761:8761"